name: NBA Stats Update

on:
  workflow_dispatch:

jobs:
  update-sheet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests gspread pandas google-auth oauth2client

      - name: Validate Google Sheets Credentials JSON
        run: |
          if [ ! -z "${{ secrets.GOOGLE_SHEETS_CREDS }}" ]; then
            echo "${{ secrets.GOOGLE_SHEETS_CREDS }}" | python -m json.tool
          else
            echo "GOOGLE_SHEETS_CREDS secret is empty or not set."
            exit 1
          fi

      - name: Create credentials file
        run: echo "${{ secrets.GOOGLE_SHEETS_CREDS }}" > credentials.json

      - name: Run script
        run: python nba_tracker.py
